name: Simple AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master, LLMRecognition]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: AI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          LANGUAGE: python
          PROMPT: |
            Review this code for ALAS (Azur Lane game automation bot). Focus on:
            1. OCR and computer vision correctness
            2. Android device connection safety  
            3. Memory leaks in automation loops
            4. Thread safety issues
            5. Performance problems in image processing
            6. Potential infinite loops or stuck states
            7. Error handling robustness
            
            Provide specific, actionable feedback with line numbers.
          EXCLUDE: "assets/**,logs/**,*.png,*.jpg,*.gif,platform-tools/**"